# Generated by Django 5.2.8 on 2025-11-20 05:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='Уровень иерархии')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chain.networknode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Узел сети',
                'verbose_name_plural': 'Узлы сети',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
                ('network_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='chain.networknode', verbose_name='Узел сети')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['level'], name='chain_netwo_level_a4b331_idx'),
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['city'], name='chain_netwo_city_12a9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['country'], name='chain_netwo_country_0fa096_idx'),
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['supplier'], name='chain_netwo_supplie_ca6546_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='chain_produ_name_8cd3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['release_date'], name='chain_produ_release_11813e_idx'),
        ),
    ]
